services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-ssl
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    networks:
      - network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - acme-data:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=davinciclaude81@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory

  nginx:
    build: services/nginx/
    container_name: nginx-internal
    env_file: .env
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - network
    volumes:
      - wordpress-data:/var/www/wordpress
    environment:
      - VIRTUAL_HOST=equancy-cloud-one.duckdns.org
      - LETSENCRYPT_HOST=equancy-cloud-one.duckdns.org
      - LETSENCRYPT_EMAIL=davinciclaude81@gmail.com

  mariadb:
    build: services/mariadb
    container_name: mariadb
    env_file: .env
    restart: unless-stopped
    expose:
      - 3306
    networks:
      - network
    volumes:
      - mariadb-data:/var/lib/mysql

  wordpress:
    build: services/wordpress/
    container_name: wordpress
    env_file: .env
    restart: unless-stopped
    expose:
      - 9000
    networks:
      - network
    volumes:
      - wordpress-data:/var/www/wordpress

  phpmyadmin:
    build: services/phpmyadmin/
    container_name: phpmyadmin
    env_file: .env
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - network
    depends_on:
      - mariadb


networks:
  network:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH:-./data}/mysql
      o: bind

  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH:-./data}/wp
      o: bind

  nginx-certs:
    driver: local

  nginx-vhost:
    driver: local

  nginx-html:
    driver: local

  acme-data:
    driver: local
